<?php
require("../../inc/header.php");

/*
		SoftName : EmpireBak Version 2010
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

DoSetDbChar('utf8');
E_D("DROP TABLE IF EXISTS `ecs_weixin_msg`;");
E_C("CREATE TABLE `ecs_weixin_msg` (
  `msgid` int(11) NOT NULL AUTO_INCREMENT,
  `uid` int(11) NOT NULL,
  `fake_id` varchar(32) NOT NULL,
  `content` text NOT NULL,
  `type` varchar(20) NOT NULL,
  `createtime` int(11) NOT NULL,
  `createymd` date NOT NULL,
  PRIMARY KEY (`msgid`),
  KEY `uid` (`uid`),
  KEY `createymd` (`createymd`),
  KEY `fake_id` (`fake_id`)
) ENGINE=MyISAM AUTO_INCREMENT=169 DEFAULT CHARSET=utf8");
E_D("replace into `ecs_weixin_msg` values('1','0','oh719wgwc5tPRNCYo9T71We6TJ9k','{&quot;event&quot;:&quot;unsubscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442915870','2015-09-22');");
E_D("replace into `ecs_weixin_msg` values('2','0','oh719wgwc5tPRNCYo9T71We6TJ9k','{&quot;event&quot;:&quot;subscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442971368','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('3','0','oh719wgwc5tPRNCYo9T71We6TJ9k','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442971705','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('4','0','oh719wsDQX4T-3Kh4beqVtXt2Ngc','{&quot;event&quot;:&quot;SCAN&quot;,&quot;key&quot;:&quot;5&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442971761','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('5','0','oh719wsDQX4T-3Kh4beqVtXt2Ngc','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://duoshv2.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442971783','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('6','0','oh719wsDQX4T-3Kh4beqVtXt2Ngc','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://duoshv2.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442971794','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('7','0','oh719wiHjf40T7L8V4cPUIDyvLZI','{&quot;event&quot;:&quot;subscribe&quot;,&quot;key&quot;:&quot;qrscene_5&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442971985','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('8','0','oh719wiHjf40T7L8V4cPUIDyvLZI','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/v_user.php&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442972000','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('9','0','oh719wiHjf40T7L8V4cPUIDyvLZI','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442972019','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('10','0','oh719wtNJ7STzuj2Y9mNqd3uwYC0','{&quot;event&quot;:&quot;subscribe&quot;,&quot;key&quot;:&quot;qrscene_6&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442972043','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('11','0','oh719wsDQX4T-3Kh4beqVtXt2Ngc','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442972080','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('12','0','oh719wtNJ7STzuj2Y9mNqd3uwYC0','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442972084','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('13','0','oh719wtNJ7STzuj2Y9mNqd3uwYC0','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442972425','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('14','0','oh719wgwc5tPRNCYo9T71We6TJ9k','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442972772','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('15','0','oh719wgwc5tPRNCYo9T71We6TJ9k','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442972833','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('16','0','oh719wgwc5tPRNCYo9T71We6TJ9k','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442972950','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('17','0','oh719wgwc5tPRNCYo9T71We6TJ9k','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442973789','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('18','0','oh719wgwc5tPRNCYo9T71We6TJ9k','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442974074','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('19','0','oh719wgwc5tPRNCYo9T71We6TJ9k','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442974135','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('20','0','oh719wiHjf40T7L8V4cPUIDyvLZI','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442974428','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('21','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442974752','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('22','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;unsubscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442974781','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('23','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;subscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442974797','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('24','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442974808','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('25','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442976801','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('26','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;unsubscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442976841','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('27','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;subscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442976861','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('28','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://www.baidu.com&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442976865','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('29','0','oh719wgwc5tPRNCYo9T71We6TJ9k','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442977765','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('30','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442977849','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('31','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;unsubscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442977872','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('32','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;subscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442977891','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('33','0','oh719wgwc5tPRNCYo9T71We6TJ9k','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442986882','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('34','0','oh719wgwc5tPRNCYo9T71We6TJ9k','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442986978','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('35','0','oh719wgwc5tPRNCYo9T71We6TJ9k','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442986999','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('36','0','oh719wgwc5tPRNCYo9T71We6TJ9k','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442987408','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('37','0','oh719wgwc5tPRNCYo9T71We6TJ9k','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442987550','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('38','0','oh719wtnD-w_8RvGVcqD2yIAo42w','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://danshanghu.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442988633','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('39','0','oh719wtnD-w_8RvGVcqD2yIAo42w','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442988804','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('40','0','oh719wtNJ7STzuj2Y9mNqd3uwYC0','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442989444','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('41','0','oh719wtNJ7STzuj2Y9mNqd3uwYC0','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442989514','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('42','0','oh719wgwc5tPRNCYo9T71We6TJ9k','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442989716','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('43','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;unsubscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442990309','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('44','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;subscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442990327','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('45','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;CLICK&quot;,&quot;key&quot;:&quot;article_133&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442990331','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('46','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;CLICK&quot;,&quot;key&quot;:&quot;article_133&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442990359','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('47','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;unsubscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442990498','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('48','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;subscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442990528','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('49','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;CLICK&quot;,&quot;key&quot;:&quot;article_133&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442990536','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('50','0','oh719wtNJ7STzuj2Y9mNqd3uwYC0','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442990552','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('51','0','oh719wgwc5tPRNCYo9T71We6TJ9k','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442990714','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('52','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;CLICK&quot;,&quot;key&quot;:&quot;article_133&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442990820','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('53','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;CLICK&quot;,&quot;key&quot;:&quot;article_133&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442990912','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('54','0','oh719wgwc5tPRNCYo9T71We6TJ9k','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442991175','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('55','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442991918','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('56','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442991993','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('57','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;unsubscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442992001','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('58','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;subscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442992010','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('59','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442992028','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('60','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442992088','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('61','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442992241','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('62','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442992633','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('63','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442993170','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('64','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442993710','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('65','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442994076','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('66','0','oh719wgwc5tPRNCYo9T71We6TJ9k','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442994085','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('67','0','oh719wsDQX4T-3Kh4beqVtXt2Ngc','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442994155','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('68','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442994447','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('69','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442994655','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('70','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;unsubscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442994796','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('71','0','oh719wsDQX4T-3Kh4beqVtXt2Ngc','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442994853','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('72','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;subscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442994862','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('73','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442994874','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('74','0','oh719wtNJ7STzuj2Y9mNqd3uwYC0','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442994913','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('75','0','oh719wgwc5tPRNCYo9T71We6TJ9k','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442995029','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('76','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442995304','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('77','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;unsubscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442995453','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('78','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;CLICK&quot;,&quot;key&quot;:&quot;info&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442995573','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('79','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;subscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442995593','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('80','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442995754','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('81','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442995949','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('82','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;CLICK&quot;,&quot;key&quot;:&quot;article_133&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442996514','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('83','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442996615','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('84','0','oh719wiHjf40T7L8V4cPUIDyvLZI','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442997074','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('85','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442997355','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('86','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442997761','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('87','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442998082','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('88','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442998135','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('89','0','oh719wgwc5tPRNCYo9T71We6TJ9k','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442998379','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('90','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442998471','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('91','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442998704','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('92','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442999587','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('93','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1442999633','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('94','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443000635','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('95','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443000758','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('96','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443000788','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('97','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443001053','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('98','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443001764','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('99','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443001906','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('100','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443002060','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('101','0','oh719wgwc5tPRNCYo9T71We6TJ9k','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443002125','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('102','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443002207','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('103','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443002295','2015-09-23');");
E_D("replace into `ecs_weixin_msg` values('104','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443055132','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('105','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443055284','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('106','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;unsubscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443055460','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('107','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;subscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443055482','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('108','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443055487','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('109','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443055669','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('110','0','oh719wgwc5tPRNCYo9T71We6TJ9k','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443055717','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('111','0','oh719wtFhW0jBYp4m-BRjt3yencc','{&quot;event&quot;:&quot;subscribe&quot;,&quot;key&quot;:&quot;qrscene_5&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443055784','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('112','0','oh719wtFhW0jBYp4m-BRjt3yencc','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443055787','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('113','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443056011','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('114','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443056077','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('115','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443056105','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('116','0','oh719wtqL4N_afTFTOo3YDOv4qoo','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443056779','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('117','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443056899','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('118','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443057036','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('119','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;CLICK&quot;,&quot;key&quot;:&quot;hot&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443057049','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('120','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443057054','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('121','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443057139','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('122','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443057281','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('123','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443057352','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('124','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;unsubscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443057457','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('125','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;subscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443057481','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('126','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443057485','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('127','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443058023','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('128','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;unsubscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443058999','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('129','0','oh719wtnD-w_8RvGVcqD2yIAo42w','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443059027','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('130','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;subscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443059028','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('131','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443059032','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('132','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443059711','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('133','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443061054','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('134','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443061349','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('135','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443061645','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('136','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443061689','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('137','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443062761','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('138','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443062843','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('139','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443063158','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('140','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443063747','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('141','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443063779','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('142','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443064122','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('143','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443064324','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('144','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443064403','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('145','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443064702','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('146','0','oh719wtqL4N_afTFTOo3YDOv4qoo','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443065056','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('147','0','oh719wp0nvhG_VH7siahRWHz38lA','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443065079','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('148','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443065538','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('149','0','oh719wluEiDa-Nnuz3cNyfuKVe90','{&quot;event&quot;:&quot;VIEW&quot;,&quot;key&quot;:&quot;http://dcityweixin.68ecshop.com/mobile/weixin/oauth.php?id=1&amp;oid=1&quot;,&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1443065691','2015-09-24');");
E_D("replace into `ecs_weixin_msg` values('150','0','oHv15jj234QmuWHhlQxMqEBjtAwU','{&quot;event&quot;:&quot;subscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1446530743','2015-11-03');");
E_D("replace into `ecs_weixin_msg` values('151','0','oHv15jj234QmuWHhlQxMqEBjtAwU','砸金蛋','text','1446530810','2015-11-03');");
E_D("replace into `ecs_weixin_msg` values('152','0','oHv15jj234QmuWHhlQxMqEBjtAwU','{&quot;event&quot;:&quot;unsubscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1446530960','2015-11-03');");
E_D("replace into `ecs_weixin_msg` values('153','0','oHv15jj234QmuWHhlQxMqEBjtAwU','{&quot;event&quot;:&quot;subscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1446530975','2015-11-03');");
E_D("replace into `ecs_weixin_msg` values('154','0','oHv15jj234QmuWHhlQxMqEBjtAwU','hot','text','1446531049','2015-11-03');");
E_D("replace into `ecs_weixin_msg` values('155','0','oHv15jj234QmuWHhlQxMqEBjtAwU','商城','text','1446531114','2015-11-03');");
E_D("replace into `ecs_weixin_msg` values('156','0','oHv15jj234QmuWHhlQxMqEBjtAwU','{&quot;event&quot;:&quot;unsubscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1446531198','2015-11-03');");
E_D("replace into `ecs_weixin_msg` values('157','0','oHv15jj234QmuWHhlQxMqEBjtAwU','{&quot;event&quot;:&quot;subscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1446531211','2015-11-03');");
E_D("replace into `ecs_weixin_msg` values('158','0','oHv15jj234QmuWHhlQxMqEBjtAwU','{&quot;event&quot;:&quot;unsubscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1446531258','2015-11-03');");
E_D("replace into `ecs_weixin_msg` values('159','0','oHv15jj234QmuWHhlQxMqEBjtAwU','{&quot;event&quot;:&quot;subscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1446531276','2015-11-03');");
E_D("replace into `ecs_weixin_msg` values('160','0','oHv15jrl4frL_JfT2i9F_V_7jFRE','购物','text','1446531954','2015-11-03');");
E_D("replace into `ecs_weixin_msg` values('161','0','oHv15jrl4frL_JfT2i9F_V_7jFRE','{&quot;event&quot;:&quot;unsubscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1446532058','2015-11-03');");
E_D("replace into `ecs_weixin_msg` values('162','0','oHv15jrl4frL_JfT2i9F_V_7jFRE','{&quot;event&quot;:&quot;subscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1446532070','2015-11-03');");
E_D("replace into `ecs_weixin_msg` values('163','0','oHv15jrl4frL_JfT2i9F_V_7jFRE','啥错','text','1446532090','2015-11-03');");
E_D("replace into `ecs_weixin_msg` values('164','0','oHv15jrl4frL_JfT2i9F_V_7jFRE','{&quot;event&quot;:&quot;unsubscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1446532631','2015-11-03');");
E_D("replace into `ecs_weixin_msg` values('165','0','oHv15jrl4frL_JfT2i9F_V_7jFRE','{&quot;event&quot;:&quot;subscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1446532647','2015-11-03');");
E_D("replace into `ecs_weixin_msg` values('166','0','oHv15jrl4frL_JfT2i9F_V_7jFRE','{&quot;event&quot;:&quot;subscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1446539443','2015-11-03');");
E_D("replace into `ecs_weixin_msg` values('167','0','oHv15jj234QmuWHhlQxMqEBjtAwU','{&quot;event&quot;:&quot;subscribe&quot;,&quot;key&quot;:{},&quot;Latitude&quot;:null,&quot;Longitude&quot;:null,&quot;Precision&quot;:null}','event','1446539636','2015-11-03');");
E_D("replace into `ecs_weixin_msg` values('168','0','oHv15jj234QmuWHhlQxMqEBjtAwU','商城','text','1446539704','2015-11-03');");

require("../../inc/footer.php");
?>